### ISSUE TITLE
Make the episode lasts longer than 50 timesteps.

### ISSUE THREAD

**Issue by samiulextreem** [qgallouedec/panda-gym#10]
Ok.pandareach env is running max 50 step and after that the env is returning done true. I intent to run the env for longer say 300 but can not find a way to do that. Can anybody provide a solution for that?

**Comment by qgallouedec** [comment]
Hello @samiulextreem ,

The easiest way to prevent the environment from returning `done=True` after 50 timesteps would be to manually register your environment. Here is how to do it:

```python
import gym
import panda_gym

gym.register(id="PandaReachLonger-v1", entry_point="panda_gym.envs:PandaReachEnv", max_episode_steps=300)

# Then, as usual:
env = gym.make("PandaReachLonger-v1")
env.reset()
# ...
```
