### ISSUE TITLE
Train files and parameter issues

### ISSUE THREAD

**Issue by x124605437** [qgallouedec/panda-gym#27]
Dear author：
I tested the Reach/PickAndPlace/Slide/Push tasks, only the PandaReach_v2 task converged，and the others failed to converge as in the paper（rXiv:2106.13687v2  [cs.LG]  19 Dec 2021）. 
Could you please show the relevant parameters for training these tasks?
Here is a part of my test code in PickAndPlace:

model = DDPG（policy=“MultiInputPolicy”， env=env，batch_size= 2048，  replay_buffer_class=HerReplayBuffer， verbose=1，  buffer_size=1000000）
model.learn（total_timesteps=10000000）

The result shows that the success rate is only 0.05

**Comment by qgallouedec** [comment]
Duplicate #21.
I'm working on it.
