### ISSUE TITLE
Are there any benchmarks about dense reward envs?

### ISSUE THREAD

**Issue by RayYoh** [qgallouedec/panda-gym#28]
I am very interesting in the dense reward envs, but I didn't find any benchmarks about them. So, can you provide some benchmarks?

**Comment by qgallouedec** [comment]
Indeed, there isn't benchmark for dense reward. However, you can easily make one using [rl-baselines3-zoo](https://github.com/DLR-RM/rl-baselines3-zoo)

After installing, run

```bash
python train.py --env PandaReach-v1 --algo tqc --env-kwargs reward_type:"'dense'"
```

> **Note**
> The current version of rl-zoo only support panda-gym v1 (with is not very different from v2). If you really want to use the v2, please use [this branch](https://github.com/qgallouedec/rl-baselines3-zoo/tree/panda_gym_v2) or wait for this [PR](https://github.com/DLR-RM/rl-baselines3-zoo/pull/244) to be merged.
