### ISSUE TITLE
Panda gym returning errors when running

### ISSUE THREAD

**Issue by MechIyad** [qgallouedec/panda-gym#31]
I found a gym environment on GitHub for robotics, I tried running it on collab without rendering with the following code

```
import gym
import panda_gym

    env = gym.make('PandaReach-v2', render=True)
    
    obs = env.reset()
    done = False
    while not done:
        action = env.action_space.sample() # random action
        obs, reward, done, info = env.step(action)
    
    env.close()
```
I got the following error

    ```
```
import gym
import panda_gym

env = gym.make('PandaReach-v2', render=True)

obs = env.reset()
done = False
while not done:
    action = env.action_space.sample() # random action
    obs, reward, done, info = env.step(action)

env.close()
```https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by qgallouedec** [comment]
Next time, please fill the issue template.

> I got the following error

What error ?
