### ISSUE TITLE
Question regarding end-effector control 

### ISSUE THREAD

**Issue by Bargez908** [qgallouedec/panda-gym#62]
In a previous answer (https://github.com/qgallouedec/panda-gym/issues/53) you said: "First, the raw action is scaled by 0.05. The result is added to the current joint position to obtain the target angles of the joints".
Can you explain how you obtain the target angles of the joint from a displacement on the end-effector? I can't find anywhere in the code.
thank you in advance!

**Comment by qgallouedec** [comment]
There are two types of environment, the environment where we control the displacement of the end-effector (`PandaReach-v3`, `PandaPush-v3`, ...), and those where we control the displacement of the joints (`PandaReachJoints-v3`, `PandaPushJoints-v3`, ...). Your question was about the environments where we control the displacement of the joints. The answer is [here](https://github.com/qgallouedec/panda-gym/issues/53#issuecomment-1518690659). For the environments where we control the end-effector displacement, the answer is [here](https://github.com/qgallouedec/panda-gym/issues/37#issuecomment-1284237047).
