### ISSUE TITLE
Cannot change the viewpoint for render.

### ISSUE THREAD

**Issue by daodreamer** [qgallouedec/panda-gym#63]
## To Reproduce

Provide a **minimal** code :

```python
import gymnasium as gym
import panda_gym

env = gym.make(
    "PandaSlide-v3",
    render_mode="rgb_array",
    renderer="OpenGL",
    render_width=480,
    render_height=480,
    render_target_position=[0.2, 0, 0],
    render_distance=1.0,
    render_yaw=90,
    render_pitch=-70,
    render_roll=0,
)
env.reset()
image = env.render()  # RGB rendering of shape (480, 480, 3)
env.close()

...
```

## System

  - OS: Ubuntu20
  - Python version (`python --version`): Python 3.9
  - Package version (`pip list | grep panda-gym`):  3.0.5

Hi there, I got a problem. I wanted to set a different viewpoint during training and test, so I followed the instruction written down in document. I changed the parameters related to render: render_yaw and render_pitch. However, when I ran the training, the viewpoint had no change at all. It's totally the same as the default. How can I change the viewpoint?

Best regards,
Dao

**Comment by qgallouedec** [comment]
The image rendered has the desired viewpoint.

```python
# The above code
from PIL import Image
Image.fromarray(image).show()
```

![image](https://user-images.githubusercontent.com/45557362/234795768-43da5ca0-e541-4e5e-b4b5-fa2cd95a71a5.png)

However, it's true the the debug GUI does not reflect that. #64 should fix it.
