### ISSUE TITLE
pybullet.error: Not connected to physics server. when closing multiple envs

### ISSUE THREAD

**Issue by kbys-t** [qgallouedec/panda-gym#7]
I got the following error when creating and closing multiple environments.
Perhaps, at close() function in PyBullet class, you need to call self.physics_client.disconnect() to specify the client id, instead of p.disconnect().

**Comment by qgallouedec** [comment]
Thank you for reporting this bug.
Indeed, I should use `self.physics_client.disconnect()` instead of `p.disconnect()`. I am correcting it.
