### ISSUE TITLE
When is it panda-gym going to be compatible with python 3.11?

### ISSUE THREAD

**Issue by RogerAylagas** [qgallouedec/panda-gym#72]
Hi,

I have seen in the [documentation](https://panda-gym.readthedocs.io/en/latest/index.html) that panda-gym is compatible until python 3.10. I am using python 3.11 in my project and I am getting the following error:

```
gymnasium.error.NameNotFound: Environment PandaReach doesn't exist.
``` 

I have followed the intallation procedure described [here](https://panda-gym.readthedocs.io/en/latest/guide/install.html).

Could you pleas help me with that?

Thank you!

**Comment by qgallouedec** [comment]
Hi, Panda-Gym should be compatible with Python 3.11 (although not stated in the doc). If you encounter this error, you've most likely forgotten to import `panda_gym`:

```python
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gymnasium as gym
>>> import panda_gym
>>> gym.make("PandaReach-v3")
pybullet build time: Aug 13 2023 10:34:42
argv[0]=--background_color_red=0.8745098114013672
argv[1]=--background_color_green=0.21176470816135406
argv[2]=--background_color_blue=0.1764705926179886
<TimeLimit<OrderEnforcing<PassiveEnvChecker<PandaReachEnv<PandaReach-v3>>>>>
```
