### ISSUE TITLE
Typo in the `core.py` script

### ISSUE THREAD

**Issue by mhz2180572509** [qgallouedec/panda-gym#75]
## Describe the bug

In the `envs/core.py` script, some the goals are defined inconsistently.

## To Fix

1. at [line 236](https://github.com/qgallouedec/panda-gym/blob/master/panda_gym/envs/core.py#L236):

```python
desired_goal_shape = observation["achieved_goal"].shape
```
=>

```python
desired_goal_shape = observation["desired_goal"].shape
```

2. and the [line 240-241](https://github.com/qgallouedec/panda-gym/blob/master/panda_gym/envs/core.py#L240):

```python
desired_goal=spaces.Box(-10.0, 10.0, shape=achieved_goal_shape, dtype=np.float32),
achieved_goal=spaces.Box(-10.0, 10.0, shape=desired_goal_shape, dtype=np.float32),
```

=>

```python
desired_goal=spaces.Box(-10.0, 10.0, shape=desired_goal_shape, dtype=np.float32),
achieved_goal=spaces.Box(-10.0, 10.0, shape=achieved_goal_shape, dtype=np.float32),
```

I found to fix this is very important, especially if we customize some environments, thanks a lot!

**Comment by qgallouedec** [comment]
thanks for reporting! Do you mind opening a PR to fix this?
