### ISSUE TITLE
Flip and Stack question

### ISSUE THREAD

**Issue by Swk6666** [qgallouedec/panda-gym#88]
Hi. The environments PandaStack-v3 and PandaFlip-v3, whether there are feasible results for them, I saw in the paper that the success rate of the stack is almost 0.

**Comment by qgallouedec** [comment]
Both are feasible, in the sense that technically, you can write your hard-coded policy that would solve the task.
However, stack has an highly spare reward, and flip required a very precise control. Both are very challenging task, but possible.

**Comment by Swk6666** [comment]
Thank you for your reply. Are there any algorithms/hyperparameters that have already been successful, or do I need to implement them myself?

**Comment by NicholasCorrado** [comment]
@Swk6666 I haven't tried PandaStack-v3, but I was able to solve PandaFlip-v3 with reasonable accuracy using the DDPG implementation in stable-baselines3.
Appendix G in [this paper](https://arxiv.org/pdf/2310.17786) lists the hyperparameters I used.
