### ISSUE TITLE
change the observation and return

### ISSUE THREAD

**Issue by ChenyangRan** [qgallouedec/panda-gym#90]
Hi, thanks for your working. My code only supports gym standard output (a, s, r, info), and I don't want the state space to be a dictionary, please tell me where I can change this output.

**Comment by qgallouedec** [comment]
Hey, I would advice to update your code to support gymnasium.
Otherwise you can wrap your environment to return done (`terminated or truncated`)
For the dict observation you can use the flatten wrapper from gymnasium
